services:
  - type: web
    name: card-game
    env: python
    buildCommand: "cd app && pip install -r requirements.txt"
    startCommand: "cd app && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
